# site settings
title: NBZIMM Tutorial
description: > 
  Learn about use of NBZIMM. 

# add the full url for the github repository
repo: "https://github.com/evanwill/go-go-ghpages"

# urls
# your gh-pages url: https://username.github.io
url: https://abbyyan3.github.io/
# your repository name: /repository
baseurl: /NBZIMM-tutorial

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
